#!/usr/bin/env bash
# A script that transfers a file from our client to a server
## 1. Accepts 4 parameters
## 2. The path to the file to be transferred
## 3. The IP of the server we want to transfer the file to
## 4. The username scp connects with
## 5. The path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
